export const API = "API";

export const SET_STOP_MARKERS = "SET_STOP_MARKERS";
export const STOP_SELECTED = "STOP_SELECTED";
export const CLEAR_STOP_SELECTED = "CLEAR_STOP_SELECTED";
export const SET_STOP_ROUTES = "SET_STOP_ROUTES";
export const SET_PREDICTIONS_FOR_STOP = "SET_PREDICTIONS_FOR_STOP";

export const SELECT_ROUTE = "SELECT_ROUTE";
export const CLEAR_ROUTE = "CLEAR_ROUTE";
export const ADD_ROUTE = "ADD_ROUTE";
export const REMOVE_ROUTE = "REMOVE_ROUTE";
export const LOAD_USER_ROUTES = "LOAD_USER_ROUTES";

export const SET_PANEL_STATE = "SET_PANEL_STATE";
export const SET_STOPS_FOR_LINE = "SET_STOPS_FOR_LINE";
